// Generated by https://quicktype.io

export interface PokemonListResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  PokemonsInfo[];
}

export interface PokemonsInfo {
    name: string;
    url:  string;
}

